---
title: 'Tidy Tuesday 2022 Week 3: Chocolate Bar Ratings'
author: "Jennifer Truong"
date: "1/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

#Load packages
library(tidyverse)
library(tidytuesdayR)
library(ggwordcloud) # For word cloud
library(showtext) # for additional fonts

## Loading Google fonts (https://fonts.google.com/)
font_add_google("Josefin Sans", "josefin")
font_add_google("Dosis", "dosis")

# Open graphics device for google fonts
op = showtext_opts(dpi = 300)
#png("dpi_300.png", 800, 800, res = 300)
#par(family = "josefin")
#par(family = "dosis")
```

```{r Get data}
tuesdata <- tidytuesdayR::tt_load('2022-01-18')
chocolate <- tuesdata$chocolate

# Source: Flavors of Cacao by Georges and Kelsey
# http://flavorsofcacao.com/chocolate_database.html
```

# Data Exploration

Let's find the top quarter of the highest rated chocolate bars.

```{r}
# Determine overall quantiles
choco_quantile <- chocolate %>%
  summarise(
    (enframe(quantile(rating, c(0.25, 0.5, 0.75)), "quantile", "rating"))
  )

# 25th percentile is 3.00, 50th percentile is 3.25, and 75th percentile is 3.50

# Filter rows with only ratings between 3.50 to 4.00
choco_75_quantile <- chocolate %>%
  filter(rating >= 3.50)
```

Let's see if we can parse out each word in most_memorable_characteristics
```{r}
# Create vector
mmc = choco_75_quantile$most_memorable_characteristics

# Start wrangling for words!
mmc_words <- choco_75_quantile %>%
  summarize(
    mmc = paste(mmc, collapse = ",") # Combine values into one cell for easier wrangling
  ) %>%
  mutate(
    word = str_split(mmc, pattern = ",") # Split so that each word is in a row
  ) %>%
  select(word) %>% # Remove first column
  unnest(word) %>% # Make each word its own row
  mutate(across(where(is.character), str_trim)) # Trim white space

```

# Build Wordcloud Plot

First, let's get a count of each word.

```{r Word Count}
# Count occurence for each word
mmc_count <- mmc_words %>%
  group_by(word) %>% # Group by word or phase
  count() 

# Find top 50 words used
mmc_top50 <- mmc_count %>% 
  arrange(-n) %>% # Arrange in descending order
  head(50)
  
```

Now let's create our wordcloud.
```{r}
# Start showtext package
showtext_auto(enable = TRUE)

# Create wordcloud
choco_cloud <- ggplot(data = mmc_top50,
                    aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n),
                      perc_step = 0.05) +
  scale_size_area(max_size = 15) +
  scale_color_gradient(low = "tan3", high = "saddlebrown") +
  labs(title = "Top 50 Memorable Qualities \n of Highly Rated Chocolate Bars",
       subtitle = "A selection of the top 50 characteristics for chocolate bars \n with a rating of at least 3.50.",
       caption = "Data: Flavors of Cacao \n Viz: @jenjentro \n #TidyTuesday 2022 W3") +
  theme(
    plot.background = element_rect(fill = "lemonchiffon"),
    plot.title = element_text(family = "josefin",
                              face = "bold", 
                              color = "saddlebrown", 
                              size = 18,
                              hjust = .5),
    plot.subtitle = element_text(family = "dosis",
                                 color = "saddlebrown", 
                                 size = 12, 
                                 hjust = .5),
    plot.caption = element_text(family = "dosis",
                                color = "saddlebrown",
                                size = 10),
    panel.background = element_rect(fill = "lemonchiffon"),
  )

choco_cloud

ggsave("choco-bar_tidytues.png", plot = choco_cloud, width = 6, height = 4.5, dpi = 300)
```

