---
title: 'Tidy Tuesday 2022 W5: Dog Breeds!'
author: "Jennifer Truong"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

#Load packages
library(tidyverse)
library(tidytuesdayR)
library(ggradar) # for radar plot
library(scales)
library(janitor) # For easier data cleaning
library(showtext) # for additional fonts

## Loading Google fonts (https://fonts.google.com/)
font_add_google("Montserrat", "montserrat")

# Open graphics device for google fonts
op = showtext_opts(dpi = 300)
#png("dpi_300.png", 800, 800, res = 300)
par(family = "montserrat")
showtext_auto(enable = TRUE)
```

```{r Load data}
# Had to read in manually this week

breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')
```

# Data Exploration

```{r Create subset}
breedtop10 <- breed_rank_all %>%
  clean_names() %>% # Change attribute names to lower case for easier coding
  select(breed, x2020_rank, links, image) %>% # Select 2020 column and other non-rank columns
  head(10) # Keep only top 10 rows

```

The top 10 are:
 [1] "Retrievers (Labrador)"         "French Bulldogs"              
 [3] "German Shepherd Dogs"          "Retrievers (Golden)"          
 [5] "Bulldogs"                      "Poodles"                      
 [7] "Beagles"                       "Rottweilers"                  
 [9] "Pointers (German Shorthaired)" "Dachshunds" 


```{r Subset trait table}
# Change attribute names in breed_traits to lower case as well
breed_traits_clean <- breed_traits %>%
  clean_names() %>%
  head(10) %>% # Look at top 10 rows
  select(breed, openness_to_strangers:mental_stimulation_needs) %>% # Remove the two non-numeric columns besides breed
  rename("Open" = "openness_to_strangers",
         "Play" = "playfulness_level",
         "Watch" = "watchdog_protective_nature",
         "Adapt" = "adaptability_level",
         "Train" = "trainability_level",
         "Energy" = "energy_level",
         "Bark" = "barking_level",
         "Needs" = "mental_stimulation_needs") # Rename for easier labeling

```

# Create plot

Okay let's create our radar plots for the top 10 breeds now!

```{r}
# Rescale data first
breed_traits_clean %>%
  mutate_at(vars(-breed), rescale) %>%
  rename("group" = "breed")
 
# Create plot
breed_radar <- breed_traits_clean %>%
  ggradar(
    grid.min = 1, grid.mid = 3, grid.max = 5,
    values.radar = c("1", "3","5"),
    grid.label.size = 3.5,
    axis.label.size = 4,
    axis.label.offset = 1.3,
    gridline.mid.colour = "gray60",
    plot.extent.x.sf = 1.5,
    plot.extent.y.sf = 1.5,
    group.line.width = 1,
    group.point.size = 1.5,
    group.colours = "navyblue"
  ) +
  facet_wrap(vars(group), ncol = 5) + # Facet wrap by breed, will be in alphabetical order
  labs(title = "Meet America's Most Popular Doggos",
       subtitle = "Personality traits of the top 10 ranked dogs in 2020 from the American Kennel Club. \n Traits are scaled from 1 (low) to 5 (high).",
       caption = "Data: American Kennel Club\n Viz: @jenjentro\n #TidyTuesday 2022 W5") +
  theme_void() +
  theme(
    text = element_text(family = "montserrat"),
    plot.background = element_rect(fill = "white"),
    plot.title = element_text(face = "bold",
                              size = 20,
                              hjust = .5),
    plot.subtitle = element_text(face = "italic",
                                 size = 14,
                                 hjust = .5),
    plot.caption = element_text(size = 12),
    plot.margin = margin(10, 10, 10, 10, unit = "pt"),
    strip.background = element_rect(fill = "navyblue", 
                                    color = NULL),
    strip.text = element_text(face = "bold",
                              color = "white",
                              margin = margin(5, 5, 5, 5),
                              size = 10),
    legend.position="none"
  )

# View plot
breed_radar
```

```{r Save plot}
ggsave("dog-breed-radar-plot.png", plot = breed_radar, height = 5, width = 11)
```

