---
title: 'TidyTuesday Week 4: Board Games'
author: "Jennifer Truong"
date: "1/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

# Load packages
library(tidyverse)
library(tidytuesdayR)
library(showtext)

## Loading Google fonts (https://fonts.google.com/)
font_add_google("Balsamiq Sans", "balsamiq")
font_add_google("Indie Flower", "indie")

# Open graphics device for google fonts if first time using fonts, comment once done
#op = showtext_opts(dpi = 300)
#png("dpi_300.png", 800, 800, res = 300)
#par(family = "balsamiq")
#par(family = "indie")
```

```{r Load data}
tuesdata <- tidytuesdayR::tt_load('2022-01-25')

ratings <- tuesdata$ratings
details <- tuesdata$details
```

Let's explore which games are the most wished games.

```{r}
# Join both tables together
games_join <- inner_join(details, ratings, by = "id", copy = FALSE, keep = FALSE)

# Create subset of top 10 wished games
top10wish <- games_join %>%
  select(boardgamecategory, wishing, name, year, rank, average, thumbnail) %>%
  arrange(-wishing) %>% # in descending order
  head(10)
```


```{r Create plot}
# Start showtext package
showtext_auto(enable = TRUE)

# Let's create a lollipop chart
top10wish_plot <- ggplot(top10wish,
                         aes(x = fct_reorder(name, wishing), 
                             y = wishing)) +
  geom_segment(aes(x = fct_reorder(name, wishing),
                   xend = fct_reorder(name, wishing), 
                   y = 0,
                   yend = wishing),
               color = "gold4",
               linetype = 2, # dashed lines
               size = 1)+
  geom_point(size = 5,
             shape = 8, # asterisk shape
             color = "gold2") +
  scale_y_continuous(lim = c(0, 20000),
                     expand = c(0,0)) + # Expand to origin
  coord_flip() +
  theme_light() +
  labs(title = "I Wish for a Board Game...",
       y = "Number wishing",
       subtitle = "What are the most requested board games in a wishlist?",
       caption = "Data: BoardGameGeek\n Viz: @jenjentro\n #TidyTuesday 2022 W4") +
  theme(
    plot.background = element_rect(fill = "navyblue"),
    plot.title = element_text(family = "balsamiq",
                              face = "bold",
                              color = "white",
                              size = 20,
                              hjust = .5),
    plot.subtitle = element_text(family = "indie",
                                 face = "italic",
                                 color = "white",
                                 size = 14, 
                                 hjust = .5),
    plot.caption = element_text(family = "indie",
                                color = "white",
                                size = 12),
    panel.background = element_rect(fill = "navyblue"),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_text(family = "balsamiq",
                                face = "bold",
                                color = "lightgoldenrod2",
                                size = 13),
    axis.text = element_text(family = "indie",
                             color = "lightgoldenrod1",
                             size = 12)
  )

top10wish_plot
```

```{r Save plot}
ggsave("board-game_tidytues.png", plot = top10wish_plot, width = 8, height = 5, dpi = 300)

```

