---
title: 'Tidy Tuesday 2022 Week 6: Tuskegee Airmen'
author: "Jennifer Truong"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

#Load packages
library(tidyverse)
library(tidytuesdayR)
library(janitor)
library(lubridate)
library(showtext)

# Load fonts 
font_add_google("Public Sans","public")
# Automatically turn on {showtext}
showtext_auto()
```

```{r Load data}
tuesdata <- tidytuesdayR::tt_load('2022-02-08')

airmen <- tuesdata$airmen
```
```{r Data wrangling}

airmen_rank <- airmen %>%
  # Rename rank at graduation column
  rename("rank" = "rank_at_graduation") %>%
  # Parse graduation date column
  mutate(
    year = year(graduation_date),
    month = month(graduation_date),
    day = day(graduation_date)
  ) %>%
  mutate(
    rank = replace(rank, rank == "Capt", "Captain"),
    rank = replace(rank, rank %in% c("Unk", "N/A"), NA)
  ) %>%
  # Filter out ranks that are unknown or NA
  drop_na(year, rank) %>%
  # Group data by year and rank
  group_by(year, rank) %>%
  # Count rows for each group
  count()

```

```{r Create plot, fig.width=2.25, fig.height=3}
airmen_plot <- ggplot(airmen_rank,
                      aes(x = year, y = n)) +
  # Use different line types to show rank
  geom_line(aes(linetype = rank),
            size = 1) +
  # Expand x-axis to origin
  scale_x_continuous(expand = c(0,0)) +
  # Flip axes
  coord_flip() +
  labs(title = "TUSKEGEE AIRMEN",
       subtitle = "RANK AT GRADUATION BY YEAR",
       y = "NUMBER OF GRADUATES",
       caption = "VIZ: @JENJENTRO | DATA: CAF (COMMEMORATIVE AIR FORCE) | #TIDYTUESDAY") +
  theme(
    text = element_text(family = "public"),
    plot.title = element_text(face = "bold",
                              size = 20,
                              hjust = 0.5),
    plot.subtitle = element_text(size = 14,
                                 hjust = 0.5),
    plot.caption = element_text(size = 10),
    plot.background = element_rect(fill="#fde4d0"),
    panel.background = element_rect(fill="#fde4d0"),
    panel.grid = element_line(color = "#f08c96"),
    axis.title.x = element_text(size = 13),
    axis.title.y = element_blank(),
    axis.text = element_text(size = 11),
    legend.title = element_blank(),
    legend.background = element_rect(fill="#fde4d0"),
    legend.key = element_rect(fill="#fde4d0"),
    legend.position = "bottom"
  )

# View plot
airmen_plot
```

```{r Save plot}
ggsave("tuskegee-line-graph.png", plot = airmen_plot, width = 5.5, height = 7, dpi = 100)

```

