---
title: 'Tidy Tuesday: Animal Crossing'
author: "Jen T. (@jenjentro)"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach packages ----

library(tidyverse)
library(janitor)
library(here)
library(forcats) # for factor variables
library(cowplot)
library(magick)

theme_set(theme_cowplot())
```

```{r Reading in ACNH Data}

# Get the Data

critic <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/critic.tsv')
user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
items <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/items.csv')
villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')

# I'll probably just focus on the villagers data though
```

Hello! Let's create a graph of villager personality types.

```{r Wrangling with villager types}

villager_count <- villagers %>%
  group_by(personality) %>% # Group by personality
  count() %>% # Count by personality
  arrange(-n) # Arrange from most villagers to least

# Change personality column to factor
villager_fct <- villager_count %>%
  mutate(personality = as_factor(personality))

# Change factor levels to based on frequncy
villager_by_freq <- villager_fct %>%
  mutate(personality = fct_infreq(personality))

#Check level
levels(villager_by_freq$personality)  
```

```{r Villager graph}

acnh_graph <- ggplot(data = villager_by_freq, 
           aes(x = fct_reorder(personality, n), # Reorder personality (x variable) by count
               y = n)) + 
  geom_bar(aes(fill = personality), # Change fill color of bars by personality type
            stat = "identity", # Use count as y variable
            show.legend = FALSE) + # Don't show legend
  labs(x = "Villager Personality", # Change axis titles
       y = "Number of Villagers",
       title = "ACNH Villager Personalities", # Give graph title
       subtitle = "Which villager personality is the most popular?") + 
  scale_fill_brewer(palette = "Dark2") + # Change fill colors of histogram bars
  geom_text(aes(label = n), # Add data labels for villager count
            color = "white", # Change font color to white
            hjust = 1.5) + # Adjust position of labels on actual bars
  scale_y_continuous(expand = c(0, 0)) + # Extend plot to start at 0
  coord_flip() + # Flip x and y axes
  theme_classic() + # Change appearance of graph
  theme(
    plot.title = element_text(hjust = 0.5), # Move graph title to center
    plot.subtitle = element_text(hjust = 0.5, face = "italic") # Move subtitle to center, put in italics
  )

acnh_graph

```
```{r Get a set of villager photos}

ggdraw() + 
    draw_plot(acnh_graph) +
    draw_image(villagers$url[villagers$name == "Anchovy"], # Get pic for lazy villager
               x = 0.10, 
               y = 0.75, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Celia"], # Get pic for normal villager
               x = 0.10, 
               y = 0.65, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Vivian"], # Get pic for snooty villager
               x = 0.10, 
               y = 0.57, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Goose"], # Get pic for jock villager
               x = 0.10, 
               y = 0.48, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Vic"], # Get pic for cranky villager 
               x = 0.10, 
               y = 0.39, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Ketchup"], # Get pic for peppy villager
               x = 0.10, 
               y = 0.30, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Raymond"], # Get pic for smug villager
               x = 0.10, 
               y = 0.23, 
               width = 0.12, 
               height = 0.12) +
    draw_image(villagers$url[villagers$name == "Phoebe"], # Get pic for uchi villager
               x = 0.10, 
               y = 0.12, 
               width = 0.12, 
               height = 0.12)
  

```

