---
title: "Tidy Tuesday - CEO Departures"
author: "Jennifer Truong"
date: "4/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

# Attach packages
library(tidyverse)
library(lubridate)
```

```{r Read in Data}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

departures <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-27/departures.csv') %>% 
  drop_na(leftofc, departure_code) %>% 
  mutate(departure_code = as.character(departure_code),
         leftofc = as_date(leftofc))

```

# Data distribution

## CEO Departures by Year

```{r}
# Let's look at departure year first
departure_year <- departures %>% 
  mutate(year = year(leftofc)) %>% 
  group_by(year) %>% 
  tally() %>% 
  filter(year < 2022) # Why is there a year 2997? Gotta remove that

# Histogram time?
ggplot(departure_year, aes(x = year)) +
  geom_histogram(bins = 20)
  
```

## CEO Depatures by Code

```{r}
# Let's look at departure year first
departure_year <- departures %>% 
  group_by(departure_code) %>% 
  tally() 

# Histogram time?
ggplot(departure_year, aes(x = departure_code)) +
  geom_histogram(bins = 30, stat="count")
```

# Plot